### ISSUE TITLE
Criação de Readme para o Modulo

### ISSUE THREAD

**Issue by lipenodias** [mentoriaiac/iac-modulo-rede-oci#3]
### Feature Request

Criar Readme para o modulo

### DoD

[ ] Descrever o funcionamento do modulo
[ ] Informar variaveis de entrada e seus tipos
[ ] Informar se o modulo possui alguma dependencia
[ ] Informar quais são as outputs

**Comment by gomex** [comment]
Usando o projeto terraform-docs fica bem mais fácil ;) 

```
docker run --rm --volume "$(pwd):/terraform-docs" -u $(id -u) quay.io/terraform-docs/terraform-docs:0.16.0 markdown /terraform-docs > README.md
```
